[package]
name = "zkpf-zcash-orchard-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
zkpf-common = { path = "../zkpf-common" }
zkpf-zcash-orchard-wallet = { path = "../zkpf-zcash-orchard-wallet" }


